### ISSUE TITLE
Invalid queries

### ISSUE THREAD

**Issue by mnboos** [geometalab/MSE-Database-Seminar-GPU-Databases#2]
Queries aren't working:

![image](https://user-images.githubusercontent.com/22575883/33758074-13e6a19c-dbfd-11e7-9afa-5a77a2490079.png)

**Comment by mnboos** [comment]
It works with the following query:

```sql
/* Query 1 */
EXPLAIN ANALYZE
SELECT cab_type_id,
       Count(*)
FROM   trips
GROUP  BY 1;
```

**Comment by Murthy10** [comment]
I know the issue (and have already fixed it a week ago)
It's in the master branche: 
https://github.com/geometalab/MSE-Database-Seminar-GPU-Databases/blob/469b5321ea37cfd4cf6722624a1431b24c46ba5e/Queries/queries.sql#L2

**Comment by mnboos** [comment]
Apologies, I thought I'd taken the queries from the master branch. Obviously not.
